#include <igraph/igraph.h>
#include <stdint.h>
#include <stdio.h>

#define TYPE_SIGNED_P(type) (((type)-1) < 0LL)

void type_name(FILE *output, int signed_p, int size) {
  if (signed_p) {
    switch (size) {
    case 1:
      fprintf(output, ":char");
      break;
    case 2:
      fprintf(output, ":short");
      break;
    case 4:
      fprintf(output, ":int");
      break;
    case 8:
      fprintf(output, ":long-long");
      break;
    default:
      goto error;
    }
  } else {
    switch (size) {
    case 1:
      fprintf(output, ":unsigned-char");
      break;
    case 2:
      fprintf(output, ":unsigned-short");
      break;
    case 4:
      fprintf(output, ":unsigned-int");
      break;
    case 8:
      fprintf(output, ":unsigned-long-long");
      break;
    default:
      goto error;
    }
  }

  return;

error:
  fprintf(output, "(error \"No type of size ~D.\" %i)\n", size);
}

int main(int argc, char **argv) {
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;

  fputs(";;;; grovel.cl\n", output);
  fputs(";;;; DO NOT MODIFY: this file has been automatically generated by "
        "c/grovel.c\n",
        output);
  fputs("(in-package #:acl-igraph)\n\n", output);

  fputs(";;; C enums and constants\n", output);

  fprintf(output, "(def-foreign-type igraph_error_type_t :int)\n");
  fprintf(output, "(def-foreign-type igraph_error_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_SUCCESS+ %i)\n", IGRAPH_SUCCESS);
  fprintf(output, "(defconstant +IGRAPH_FAILURE+ %i)\n", IGRAPH_FAILURE);
  fprintf(output, "(defconstant +IGRAPH_ENOMEM+ %i)\n", IGRAPH_ENOMEM);
  fprintf(output, "(defconstant +IGRAPH_PARSEERROR+ %i)\n", IGRAPH_PARSEERROR);
  fprintf(output, "(defconstant +IGRAPH_EINVAL+ %i)\n", IGRAPH_EINVAL);
  fprintf(output, "(defconstant +IGRAPH_EXISTS+ %i)\n", IGRAPH_EXISTS);
  fprintf(output, "(defconstant +IGRAPH_EINVEVECTOR+ %i)\n",
          IGRAPH_EINVEVECTOR);
  fprintf(output, "(defconstant +IGRAPH_EINVVID+ %i)\n", IGRAPH_EINVVID);
  fprintf(output, "(defconstant +IGRAPH_NONSQUARE+ %i)\n", IGRAPH_NONSQUARE);
  fprintf(output, "(defconstant +IGRAPH_EINVMODE+ %i)\n", IGRAPH_EINVMODE);
  fprintf(output, "(defconstant +IGRAPH_EFILE+ %i)\n", IGRAPH_EFILE);
  fprintf(output, "(defconstant +IGRAPH_UNIMPLEMENTED+ %i)\n",
          IGRAPH_UNIMPLEMENTED);
  fprintf(output, "(defconstant +IGRAPH_INTERRUPTED+ %i)\n",
          IGRAPH_INTERRUPTED);
  fprintf(output, "(defconstant +IGRAPH_DIVERGED+ %i)\n", IGRAPH_DIVERGED);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_PROD+ %i)\n",
          IGRAPH_ARPACK_PROD);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NPOS+ %i)\n",
          IGRAPH_ARPACK_NPOS);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NEVNPOS+ %i)\n",
          IGRAPH_ARPACK_NEVNPOS);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NCVSMALL+ %i)\n",
          IGRAPH_ARPACK_NCVSMALL);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NONPOSI+ %i)\n",
          IGRAPH_ARPACK_NONPOSI);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_WHICHINV+ %i)\n",
          IGRAPH_ARPACK_WHICHINV);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_BMATINV+ %i)\n",
          IGRAPH_ARPACK_BMATINV);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_WORKLSMALL+ %i)\n",
          IGRAPH_ARPACK_WORKLSMALL);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_TRIDERR+ %i)\n",
          IGRAPH_ARPACK_TRIDERR);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_ZEROSTART+ %i)\n",
          IGRAPH_ARPACK_ZEROSTART);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_MODEINV+ %i)\n",
          IGRAPH_ARPACK_MODEINV);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_MODEBMAT+ %i)\n",
          IGRAPH_ARPACK_MODEBMAT);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_ISHIFT+ %i)\n",
          IGRAPH_ARPACK_ISHIFT);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NEVBE+ %i)\n",
          IGRAPH_ARPACK_NEVBE);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NOFACT+ %i)\n",
          IGRAPH_ARPACK_NOFACT);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_FAILED+ %i)\n",
          IGRAPH_ARPACK_FAILED);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_HOWMNY+ %i)\n",
          IGRAPH_ARPACK_HOWMNY);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_HOWMNYS+ %i)\n",
          IGRAPH_ARPACK_HOWMNYS);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_EVDIFF+ %i)\n",
          IGRAPH_ARPACK_EVDIFF);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_SHUR+ %i)\n",
          IGRAPH_ARPACK_SHUR);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_LAPACK+ %i)\n",
          IGRAPH_ARPACK_LAPACK);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_UNKNOWN+ %i)\n",
          IGRAPH_ARPACK_UNKNOWN);
  fprintf(output, "(defconstant +IGRAPH_ENEGLOOP+ %i)\n", IGRAPH_ENEGLOOP);
  fprintf(output, "(defconstant +IGRAPH_EINTERNAL+ %i)\n", IGRAPH_EINTERNAL);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_MAXIT+ %i)\n",
          IGRAPH_ARPACK_MAXIT);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_NOSHIFT+ %i)\n",
          IGRAPH_ARPACK_NOSHIFT);
  fprintf(output, "(defconstant +IGRAPH_ARPACK_REORDER+ %i)\n",
          IGRAPH_ARPACK_REORDER);
  fprintf(output, "(defconstant +IGRAPH_EDIVZERO+ %i)\n", IGRAPH_EDIVZERO);
  fprintf(output, "(defconstant +IGRAPH_GLP_EBOUND+ %i)\n", IGRAPH_GLP_EBOUND);
  fprintf(output, "(defconstant +IGRAPH_GLP_EROOT+ %i)\n", IGRAPH_GLP_EROOT);
  fprintf(output, "(defconstant +IGRAPH_GLP_ENOPFS+ %i)\n", IGRAPH_GLP_ENOPFS);
  fprintf(output, "(defconstant +IGRAPH_GLP_ENODFS+ %i)\n", IGRAPH_GLP_ENODFS);
  fprintf(output, "(defconstant +IGRAPH_GLP_EFAIL+ %i)\n", IGRAPH_GLP_EFAIL);
  fprintf(output, "(defconstant +IGRAPH_GLP_EMIPGAP+ %i)\n",
          IGRAPH_GLP_EMIPGAP);
  fprintf(output, "(defconstant +IGRAPH_GLP_ETMLIM+ %i)\n", IGRAPH_GLP_ETMLIM);
  fprintf(output, "(defconstant +IGRAPH_GLP_ESTOP+ %i)\n", IGRAPH_GLP_ESTOP);
  fprintf(output, "(defconstant +IGRAPH_EATTRIBUTES+ %i)\n",
          IGRAPH_EATTRIBUTES);
  fprintf(output, "(defconstant +IGRAPH_EATTRCOMBINE+ %i)\n",
          IGRAPH_EATTRCOMBINE);
  fprintf(output, "(defconstant +IGRAPH_ELAPACK+ %i)\n", IGRAPH_ELAPACK);
  fprintf(output, "(defconstant +IGRAPH_EOVERFLOW+ %i)\n", IGRAPH_EOVERFLOW);
  fprintf(output, "(defconstant +IGRAPH_EGLP+ %i)\n", IGRAPH_EGLP);
  fprintf(output, "(defconstant +IGRAPH_CPUTIME+ %i)\n", IGRAPH_CPUTIME);
  fprintf(output, "(defconstant +IGRAPH_EUNDERFLOW+ %i)\n", IGRAPH_EUNDERFLOW);
  fprintf(output, "(defconstant +IGRAPH_ERWSTUCK+ %i)\n", IGRAPH_ERWSTUCK);
  fprintf(output, "(defconstant +IGRAPH_STOP+ %i)\n", IGRAPH_STOP);
  fprintf(output, "(defconstant +IGRAPH_ERANGE+ %i)\n", IGRAPH_ERANGE);
  fprintf(output, "(defconstant +IGRAPH_ENOSOL+ %i)\n", IGRAPH_ENOSOL);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_i_directed_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_UNDIRECTED+ %i)\n", IGRAPH_UNDIRECTED);
  fprintf(output, "(defconstant +IGRAPH_DIRECTED+ %i)\n", IGRAPH_DIRECTED);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_loops_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_NO_LOOPS+ %i)\n", IGRAPH_NO_LOOPS);
  fprintf(output, "(defconstant +IGRAPH_LOOPS+ %i)\n", IGRAPH_LOOPS);
  fprintf(output, "(defconstant +IGRAPH_LOOPS_TWICE+ %i)\n",
          IGRAPH_LOOPS_TWICE);
  fprintf(output, "(defconstant +IGRAPH_LOOPS_ONCE+ %i)\n", IGRAPH_LOOPS_ONCE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_multiple_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_NO_MULTIPLE+ %i)\n",
          IGRAPH_NO_MULTIPLE);
  fprintf(output, "(defconstant +IGRAPH_MULTIPLE+ %i)\n", IGRAPH_MULTIPLE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_order_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_ASCENDING+ %i)\n", IGRAPH_ASCENDING);
  fprintf(output, "(defconstant +IGRAPH_DESCENDING+ %i)\n", IGRAPH_DESCENDING);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_optimal_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_MINIMUM+ %i)\n", IGRAPH_MINIMUM);
  fprintf(output, "(defconstant +IGRAPH_MAXIMUM+ %i)\n", IGRAPH_MAXIMUM);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_neimode_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_OUT+ %i)\n", IGRAPH_OUT);
  fprintf(output, "(defconstant +IGRAPH_IN+ %i)\n", IGRAPH_IN);
  fprintf(output, "(defconstant +IGRAPH_ALL+ %i)\n", IGRAPH_ALL);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_connectedness_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_WEAK+ %i)\n", IGRAPH_WEAK);
  fprintf(output, "(defconstant +IGRAPH_STRONG+ %i)\n", IGRAPH_STRONG);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_reciprocity_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_RECIPROCITY_DEFAULT+ %i)\n",
          IGRAPH_RECIPROCITY_DEFAULT);
  fprintf(output, "(defconstant +IGRAPH_RECIPROCITY_RATIO+ %i)\n",
          IGRAPH_RECIPROCITY_RATIO);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_adjacency_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_ADJ_DIRECTED+ %i)\n",
          IGRAPH_ADJ_DIRECTED);
  fprintf(output, "(defconstant +IGRAPH_ADJ_UNDIRECTED+ %i)\n",
          IGRAPH_ADJ_UNDIRECTED);
  fprintf(output, "(defconstant +IGRAPH_ADJ_UPPER+ %i)\n", IGRAPH_ADJ_UPPER);
  fprintf(output, "(defconstant +IGRAPH_ADJ_LOWER+ %i)\n", IGRAPH_ADJ_LOWER);
  fprintf(output, "(defconstant +IGRAPH_ADJ_MIN+ %i)\n", IGRAPH_ADJ_MIN);
  fprintf(output, "(defconstant +IGRAPH_ADJ_PLUS+ %i)\n", IGRAPH_ADJ_PLUS);
  fprintf(output, "(defconstant +IGRAPH_ADJ_MAX+ %i)\n", IGRAPH_ADJ_MAX);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_star_mode_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_STAR_OUT+ %i)\n", IGRAPH_STAR_OUT);
  fprintf(output, "(defconstant +IGRAPH_STAR_IN+ %i)\n", IGRAPH_STAR_IN);
  fprintf(output, "(defconstant +IGRAPH_STAR_UNDIRECTED+ %i)\n",
          IGRAPH_STAR_UNDIRECTED);
  fprintf(output, "(defconstant +IGRAPH_STAR_MUTUAL+ %i)\n",
          IGRAPH_STAR_MUTUAL);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_wheel_mode_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_WHEEL_OUT+ %i)\n", IGRAPH_WHEEL_OUT);
  fprintf(output, "(defconstant +IGRAPH_WHEEL_IN+ %i)\n", IGRAPH_WHEEL_IN);
  fprintf(output, "(defconstant +IGRAPH_WHEEL_UNDIRECTED+ %i)\n",
          IGRAPH_WHEEL_UNDIRECTED);
  fprintf(output, "(defconstant +IGRAPH_WHEEL_MUTUAL+ %i)\n",
          IGRAPH_WHEEL_MUTUAL);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_tree_mode_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_TREE_OUT+ %i)\n", IGRAPH_TREE_OUT);
  fprintf(output, "(defconstant +IGRAPH_TREE_IN+ %i)\n", IGRAPH_TREE_IN);
  fprintf(output, "(defconstant +IGRAPH_TREE_UNDIRECTED+ %i)\n",
          IGRAPH_TREE_UNDIRECTED);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_erdos_renyi_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_ERDOS_RENYI_GNP+ %i)\n",
          IGRAPH_ERDOS_RENYI_GNP);
  fprintf(output, "(defconstant +IGRAPH_ERDOS_RENYI_GNM+ %i)\n",
          IGRAPH_ERDOS_RENYI_GNM);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_get_adjacency_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_GET_ADJACENCY_UPPER+ %i)\n",
          IGRAPH_GET_ADJACENCY_UPPER);
  fprintf(output, "(defconstant +IGRAPH_GET_ADJACENCY_LOWER+ %i)\n",
          IGRAPH_GET_ADJACENCY_LOWER);
  fprintf(output, "(defconstant +IGRAPH_GET_ADJACENCY_BOTH+ %i)\n",
          IGRAPH_GET_ADJACENCY_BOTH);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_degseq_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_DEGSEQ_CONFIGURATION+ %i)\n",
          IGRAPH_DEGSEQ_CONFIGURATION);
  fprintf(output, "(defconstant +IGRAPH_DEGSEQ_VL+ %i)\n", IGRAPH_DEGSEQ_VL);
  fprintf(output, "(defconstant +IGRAPH_DEGSEQ_FAST_HEUR_SIMPLE+ %i)\n",
          IGRAPH_DEGSEQ_FAST_HEUR_SIMPLE);
  fprintf(output, "(defconstant +IGRAPH_DEGSEQ_CONFIGURATION_SIMPLE+ %i)\n",
          IGRAPH_DEGSEQ_CONFIGURATION_SIMPLE);
  fprintf(output, "(defconstant +IGRAPH_DEGSEQ_EDGE_SWITCHING_SIMPLE+ %i)\n",
          IGRAPH_DEGSEQ_EDGE_SWITCHING_SIMPLE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_realize_degseq_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_REALIZE_DEGSEQ_SMALLEST+ %i)\n",
          IGRAPH_REALIZE_DEGSEQ_SMALLEST);
  fprintf(output, "(defconstant +IGRAPH_REALIZE_DEGSEQ_LARGEST+ %i)\n",
          IGRAPH_REALIZE_DEGSEQ_LARGEST);
  fprintf(output, "(defconstant +IGRAPH_REALIZE_DEGSEQ_INDEX+ %i)\n",
          IGRAPH_REALIZE_DEGSEQ_INDEX);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_random_tree_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_RANDOM_TREE_PRUFER+ %i)\n",
          IGRAPH_RANDOM_TREE_PRUFER);
  fprintf(output, "(defconstant +IGRAPH_RANDOM_TREE_LERW+ %i)\n",
          IGRAPH_RANDOM_TREE_LERW);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_fileformat_type_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_FILEFORMAT_EDGELIST+ %i)\n",
          IGRAPH_FILEFORMAT_EDGELIST);
  fprintf(output, "(defconstant +IGRAPH_FILEFORMAT_NCOL+ %i)\n",
          IGRAPH_FILEFORMAT_NCOL);
  fprintf(output, "(defconstant +IGRAPH_FILEFORMAT_PAJEK+ %i)\n",
          IGRAPH_FILEFORMAT_PAJEK);
  fprintf(output, "(defconstant +IGRAPH_FILEFORMAT_LGL+ %i)\n",
          IGRAPH_FILEFORMAT_LGL);
  fprintf(output, "(defconstant +IGRAPH_FILEFORMAT_GRAPHML+ %i)\n",
          IGRAPH_FILEFORMAT_GRAPHML);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_rewiring_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_REWIRING_SIMPLE+ %i)\n",
          IGRAPH_REWIRING_SIMPLE);
  fprintf(output, "(defconstant +IGRAPH_REWIRING_SIMPLE_LOOPS+ %i)\n",
          IGRAPH_REWIRING_SIMPLE_LOOPS);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_edgeorder_type_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_EDGEORDER_ID+ %i)\n",
          IGRAPH_EDGEORDER_ID);
  fprintf(output, "(defconstant +IGRAPH_EDGEORDER_FROM+ %i)\n",
          IGRAPH_EDGEORDER_FROM);
  fprintf(output, "(defconstant +IGRAPH_EDGEORDER_TO+ %i)\n",
          IGRAPH_EDGEORDER_TO);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_to_directed_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_TO_DIRECTED_ARBITRARY+ %i)\n",
          IGRAPH_TO_DIRECTED_ARBITRARY);
  fprintf(output, "(defconstant +IGRAPH_TO_DIRECTED_MUTUAL+ %i)\n",
          IGRAPH_TO_DIRECTED_MUTUAL);
  fprintf(output, "(defconstant +IGRAPH_TO_DIRECTED_RANDOM+ %i)\n",
          IGRAPH_TO_DIRECTED_RANDOM);
  fprintf(output, "(defconstant +IGRAPH_TO_DIRECTED_ACYCLIC+ %i)\n",
          IGRAPH_TO_DIRECTED_ACYCLIC);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_to_undirected_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_TO_UNDIRECTED_EACH+ %i)\n",
          IGRAPH_TO_UNDIRECTED_EACH);
  fprintf(output, "(defconstant +IGRAPH_TO_UNDIRECTED_COLLAPSE+ %i)\n",
          IGRAPH_TO_UNDIRECTED_COLLAPSE);
  fprintf(output, "(defconstant +IGRAPH_TO_UNDIRECTED_MUTUAL+ %i)\n",
          IGRAPH_TO_UNDIRECTED_MUTUAL);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_vconn_nei_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_VCONN_NEI_ERROR+ %i)\n",
          IGRAPH_VCONN_NEI_ERROR);
  fprintf(output, "(defconstant +IGRAPH_VCONN_NEI_NUMBER_OF_NODES+ %i)\n",
          IGRAPH_VCONN_NEI_NUMBER_OF_NODES);
  fprintf(output, "(defconstant +IGRAPH_VCONN_NEI_IGNORE+ %i)\n",
          IGRAPH_VCONN_NEI_IGNORE);
  fprintf(output, "(defconstant +IGRAPH_VCONN_NEI_NEGATIVE+ %i)\n",
          IGRAPH_VCONN_NEI_NEGATIVE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_spincomm_update_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_SPINCOMM_UPDATE_SIMPLE+ %i)\n",
          IGRAPH_SPINCOMM_UPDATE_SIMPLE);
  fprintf(output, "(defconstant +IGRAPH_SPINCOMM_UPDATE_CONFIG+ %i)\n",
          IGRAPH_SPINCOMM_UPDATE_CONFIG);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_lazy_adlist_simplify_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_DONT_SIMPLIFY+ %i)\n",
          IGRAPH_DONT_SIMPLIFY);
  fprintf(output, "(defconstant +IGRAPH_SIMPLIFY+ %i)\n", IGRAPH_SIMPLIFY);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_transitivity_mode_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_TRANSITIVITY_NAN+ %i)\n",
          IGRAPH_TRANSITIVITY_NAN);
  fprintf(output, "(defconstant +IGRAPH_TRANSITIVITY_ZERO+ %i)\n",
          IGRAPH_TRANSITIVITY_ZERO);
  fputs("\n", output);

  fprintf(output,
          "(def-foreign-type igraph_spinglass_implementation_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_SPINCOMM_IMP_ORIG+ %i)\n",
          IGRAPH_SPINCOMM_IMP_ORIG);
  fprintf(output, "(defconstant +IGRAPH_SPINCOMM_IMP_NEG+ %i)\n",
          IGRAPH_SPINCOMM_IMP_NEG);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_community_comparison_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_COMMCMP_VI+ %i)\n", IGRAPH_COMMCMP_VI);
  fprintf(output, "(defconstant +IGRAPH_COMMCMP_NMI+ %i)\n",
          IGRAPH_COMMCMP_NMI);
  fprintf(output, "(defconstant +IGRAPH_COMMCMP_SPLIT_JOIN+ %i)\n",
          IGRAPH_COMMCMP_SPLIT_JOIN);
  fprintf(output, "(defconstant +IGRAPH_COMMCMP_RAND+ %i)\n",
          IGRAPH_COMMCMP_RAND);
  fprintf(output, "(defconstant +IGRAPH_COMMCMP_ADJUSTED_RAND+ %i)\n",
          IGRAPH_COMMCMP_ADJUSTED_RAND);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_add_weights_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_ADD_WEIGHTS_NO+ %i)\n",
          IGRAPH_ADD_WEIGHTS_NO);
  fprintf(output, "(defconstant +IGRAPH_ADD_WEIGHTS_YES+ %i)\n",
          IGRAPH_ADD_WEIGHTS_YES);
  fprintf(output, "(defconstant +IGRAPH_ADD_WEIGHTS_IF_PRESENT+ %i)\n",
          IGRAPH_ADD_WEIGHTS_IF_PRESENT);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_barabasi_algorithm_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_BARABASI_BAG+ %i)\n",
          IGRAPH_BARABASI_BAG);
  fprintf(output, "(defconstant +IGRAPH_BARABASI_PSUMTREE+ %i)\n",
          IGRAPH_BARABASI_PSUMTREE);
  fprintf(output, "(defconstant +IGRAPH_BARABASI_PSUMTREE_MULTIPLE+ %i)\n",
          IGRAPH_BARABASI_PSUMTREE_MULTIPLE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_fas_algorithm_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_FAS_EXACT_IP+ %i)\n",
          IGRAPH_FAS_EXACT_IP);
  fprintf(output, "(defconstant +IGRAPH_FAS_APPROX_EADES+ %i)\n",
          IGRAPH_FAS_APPROX_EADES);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_subgraph_implementation_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_SUBGRAPH_AUTO+ %i)\n",
          IGRAPH_SUBGRAPH_AUTO);
  fprintf(output, "(defconstant +IGRAPH_SUBGRAPH_COPY_AND_DELETE+ %i)\n",
          IGRAPH_SUBGRAPH_COPY_AND_DELETE);
  fprintf(output, "(defconstant +IGRAPH_SUBGRAPH_CREATE_FROM_SCRATCH+ %i)\n",
          IGRAPH_SUBGRAPH_CREATE_FROM_SCRATCH);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_imitate_algorithm_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_IMITATE_AUGMENTED+ %i)\n",
          IGRAPH_IMITATE_AUGMENTED);
  fprintf(output, "(defconstant +IGRAPH_IMITATE_BLIND+ %i)\n",
          IGRAPH_IMITATE_BLIND);
  fprintf(output, "(defconstant +IGRAPH_IMITATE_CONTRACTED+ %i)\n",
          IGRAPH_IMITATE_CONTRACTED);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_layout_grid_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_LAYOUT_GRID+ %i)\n",
          IGRAPH_LAYOUT_GRID);
  fprintf(output, "(defconstant +IGRAPH_LAYOUT_NOGRID+ %i)\n",
          IGRAPH_LAYOUT_NOGRID);
  fprintf(output, "(defconstant +IGRAPH_LAYOUT_AUTOGRID+ %i)\n",
          IGRAPH_LAYOUT_AUTOGRID);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_random_walk_stuck_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_RANDOM_WALK_STUCK_ERROR+ %i)\n",
          IGRAPH_RANDOM_WALK_STUCK_ERROR);
  fprintf(output, "(defconstant +IGRAPH_RANDOM_WALK_STUCK_RETURN+ %i)\n",
          IGRAPH_RANDOM_WALK_STUCK_RETURN);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_voronoi_tiebreaker_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_VORONOI_FIRST+ %i)\n",
          IGRAPH_VORONOI_FIRST);
  fprintf(output, "(defconstant +IGRAPH_VORONOI_LAST+ %i)\n",
          IGRAPH_VORONOI_LAST);
  fprintf(output, "(defconstant +IGRAPH_VORONOI_RANDOM+ %i)\n",
          IGRAPH_VORONOI_RANDOM);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_matrix_storage_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_ROW_MAJOR+ %i)\n", IGRAPH_ROW_MAJOR);
  fprintf(output, "(defconstant +IGRAPH_COLUMN_MAJOR+ %i)\n",
          IGRAPH_COLUMN_MAJOR);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_cached_property_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_PROP_HAS_LOOP+ %i)\n",
          IGRAPH_PROP_HAS_LOOP);
  fprintf(output, "(defconstant +IGRAPH_PROP_HAS_MULTI+ %i)\n",
          IGRAPH_PROP_HAS_MULTI);
  fprintf(output, "(defconstant +IGRAPH_PROP_HAS_MUTUAL+ %i)\n",
          IGRAPH_PROP_HAS_MUTUAL);
  fprintf(output, "(defconstant +IGRAPH_PROP_IS_WEAKLY_CONNECTED+ %i)\n",
          IGRAPH_PROP_IS_WEAKLY_CONNECTED);
  fprintf(output, "(defconstant +IGRAPH_PROP_IS_STRONGLY_CONNECTED+ %i)\n",
          IGRAPH_PROP_IS_STRONGLY_CONNECTED);
  fprintf(output, "(defconstant +IGRAPH_PROP_IS_DAG+ %i)\n",
          IGRAPH_PROP_IS_DAG);
  fprintf(output, "(defconstant +IGRAPH_PROP_IS_FOREST+ %i)\n",
          IGRAPH_PROP_IS_FOREST);
  fprintf(output, "(defconstant +IGRAPH_PROP_I_SIZE+ %i)\n",
          IGRAPH_PROP_I_SIZE);
  fputs("\n", output);

  fprintf(output, "(def-foreign-type igraph_vs_type_t :int)\n");
  fprintf(output, "(defconstant +IGRAPH_VS_ALL+ %i)\n", IGRAPH_VS_ALL);
  fprintf(output, "(defconstant +IGRAPH_VS_ADJ+ %i)\n", IGRAPH_VS_ADJ);
  fprintf(output, "(defconstant +IGRAPH_VS_NONE+ %i)\n", IGRAPH_VS_NONE);
  fprintf(output, "(defconstant +IGRAPH_VS_1+ %i)\n", IGRAPH_VS_1);
  fprintf(output, "(defconstant +IGRAPH_VS_VECTORPTR+ %i)\n",
          IGRAPH_VS_VECTORPTR);
  fprintf(output, "(defconstant +IGRAPH_VS_VECTOR+ %i)\n", IGRAPH_VS_VECTOR);
  fprintf(output, "(defconstant +IGRAPH_VS_RANGE+ %i)\n", IGRAPH_VS_RANGE);
  fprintf(output, "(defconstant +IGRAPH_VS_NONADJ+ %i)\n", IGRAPH_VS_NONADJ);
  fputs("\n", output);

  fprintf(output, "(defconstant +IGRAPH_INTEGER_MIN+ %ld)\n",
          IGRAPH_INTEGER_MIN);
  fprintf(output, "(defconstant +IGRAPH_INTEGER_MAX+ %ld)\n",
          IGRAPH_INTEGER_MAX);
  /* fprintf (output, "(defconstant +IGRAPH_UINT_MIN+ %lu)\n", */
  /*          UINT64_MIN); */
  fprintf(output, "(defconstant +IGRAPH_UINT_MAX+ %lu)\n", IGRAPH_UINT_MAX);
  fputs("\n", output);

  fprintf(output, "(defconstant +IGRAPH_VCOUNT_MAX+ %lu)\n", IGRAPH_VCOUNT_MAX);
  fprintf(output, "(defconstant +IGRAPH_ECOUNT_MAX+ %lu)\n", IGRAPH_ECOUNT_MAX);
  fputs("\n", output);

  fputs(";;; C types\n", output);

  fputs("(def-foreign-type uint8_t ", output);
  type_name(output, TYPE_SIGNED_P(uint8_t), sizeof(uint8_t));
  fputs(")\n", output);

  fputs("(def-foreign-type igraph_integer_t ", output);
  type_name(output, TYPE_SIGNED_P(igraph_integer_t), sizeof(igraph_integer_t));
  fputs(")\n", output);

  fputs("(def-foreign-type igraph_uint_t ", output);
  type_name(output, TYPE_SIGNED_P(igraph_uint_t), sizeof(igraph_uint_t));
  fputs(")\n", output);

  fputs("(def-foreign-type igraph_real_t :double)\n", output);

  fputs("(def-foreign-type igraph_bool_t ", output);
  type_name(output, TYPE_SIGNED_P(igraph_bool_t), sizeof(igraph_bool_t));
  fputs(")\n", output);

  fprintf(output,
          "(def-foreign-type igraph_attribute_combination_t (:array "
          ":unsigned-char %zu))\n",
          sizeof(igraph_attribute_combination_t));

  return 0;
}
